### ISSUE TITLE
OSX builds are not signed / refused to run

### ISSUE THREAD

**Issue by ayan4m1** [ysmood/use-node#2]
The OS X binary cannot be run on a Mac laptop running Catalina. It says something about the binary not being signed or secure. Does not allow you to bypass, you can only move the file to the trash.

Trying to get a 200 person team using this utility but no OSX support is a non-starter.

**Comment by ysmood** [comment]
https://support.apple.com/en-hk/guide/mac-help/mh40616/10.15/mac/10.15

**Comment by ysmood** [comment]
You can also build and code signing it by yourself. Install golang then:

```go
go install github.com/ysmood/use-node@latest
```

**Comment by ayan4m1** [comment]
Thank you for the information, I will try this with my team and hope it works out well.
